# Generated by Django 4.1.10 on 2024-12-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=255)),
                ('group_id', models.IntegerField()),
                ('running', models.BooleanField(default=False)),
                ('owner_id', models.IntegerField()),
                ('libname', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
        migrations.CreateModel(
            name='VkConfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Коды подтверждения',
            },
        ),
    ]
