# Generated by Django 4.1.10 on 2024-12-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_confirmcode_group_payment_wallet_delete_vkconfirm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='lib',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
