# Generated by Django 4.1.10 on 2024-12-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bot_lib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='lib',
            field=models.CharField(blank=True, default='bottest01', max_length=100, null=True),
        ),
    ]
