# Generated by Django 4.1.10 on 2024-12-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bot_lib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='lib',
            field=models.CharField(default='bottest01', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.IntegerField(choices=[(0, 'Wait'), (1, 'Verifying'), (2, 'Verify'), (-1, 'Error')], default=0),
        ),
    ]
