# Generated by Django 4.1.10 on 2024-12-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bot_lib_alter_group_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
