# Generated by Django 5.2.2 on 2025-06-04 21:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VKGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID группы в ВК"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("Новый", "Новый"),
                            ("Ожидает", "Ожидает"),
                            ("Успешно", "Успешно"),
                            ("Ошибка", "Ошибка"),
                        ],
                        default="Новый",
                        max_length=20,
                        verbose_name="Статус верификации",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        max_length=255, verbose_name="Токен доступа группы"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец группы",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfirmCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, verbose_name="Код")),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата"
                    ),
                ),
                (
                    "vk_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.vkgroup",
                        verbose_name="ID группы",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название чат-бота"),
                ),
                (
                    "library_path",
                    models.CharField(
                        max_length=255, verbose_name="Путь до библиотеки бота"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Активен", "Активен"), ("Неактивен", "Неактивен")],
                        default="Неактивен",
                        max_length=20,
                        verbose_name="Состояние",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=549.0,
                        max_digits=10,
                        verbose_name="Стоимость",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ID пользователя",
                    ),
                ),
                (
                    "vk_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.vkgroup",
                        verbose_name="ID группы ВК",
                    ),
                ),
            ],
        ),
    ]
