# Generated by Django 5.2.2 on 2025-06-04 21:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_vkgroup_confirmcode_chatbot"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата"
                    ),
                ),
                (
                    "messages_processed",
                    models.IntegerField(default=0, verbose_name="Обработано сообщений"),
                ),
                (
                    "interactions",
                    models.IntegerField(default=0, verbose_name="Взаимодействия"),
                ),
                (
                    "active_users",
                    models.JSONField(
                        default=list, verbose_name="Активные пользователи"
                    ),
                ),
                (
                    "chat_bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.chatbot",
                        verbose_name="Чат-бот",
                    ),
                ),
            ],
            options={
                "unique_together": {("chat_bot", "date")},
            },
        ),
        migrations.CreateModel(
            name="GroupStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата"
                    ),
                ),
                (
                    "subscribers",
                    models.IntegerField(default=0, verbose_name="Подписчики"),
                ),
                ("likes", models.IntegerField(default=0, verbose_name="Лайки")),
                ("messages", models.IntegerField(default=0, verbose_name="Сообщения")),
                (
                    "activity_score",
                    models.IntegerField(default=0, verbose_name="Счет активности"),
                ),
                (
                    "vk_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.vkgroup",
                        verbose_name="Группа ВК",
                    ),
                ),
            ],
            options={
                "unique_together": {("vk_group", "date")},
            },
        ),
    ]
