# Generated by Django 5.2.2 on 2025-06-05 05:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_botstatistics_groupstatistics"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="botstatistics",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="groupstatistics",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="chatbot",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="chatbot",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userbalance",
            name="last_payment",
        ),
        migrations.AddField(
            model_name="vkgroup",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="botstatistics",
            name="active_users",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="botstatistics",
            name="chat_bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.chatbot"
            ),
        ),
        migrations.AlterField(
            model_name="botstatistics",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="botstatistics",
            name="interactions",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="botstatistics",
            name="messages_processed",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="library_path",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="status",
            field=models.CharField(default="Неактивен", max_length=50),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="vk_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.vkgroup"
            ),
        ),
        migrations.AlterField(
            model_name="confirmcode",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="confirmcode",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="confirmcode",
            name="vk_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.vkgroup"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="groupstatistics",
            name="activity_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="groupstatistics",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="groupstatistics",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="groupstatistics",
            name="messages",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="groupstatistics",
            name="subscribers",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="groupstatistics",
            name="vk_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.vkgroup"
            ),
        ),
        migrations.AlterField(
            model_name="vkgroup",
            name="access_token",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="vkgroup",
            name="group_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="vkgroup",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="vkgroup",
            name="verification_status",
            field=models.CharField(default="Новый", max_length=50),
        ),
    ]
